version: '3'

services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:5000
    depends_on:
      - backend
    networks: 
      - public

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgres://postgres:devpass@db:5432/devdb
      - BASE_URL=http://localhost:5000
      - PORT=5000
      - CLIENT_URL=http://localhost:5173
      - TOKEN_SECRET=GdKHRJCT2F
      - TOKEN_EXPIRATION_SECONDS=604800
    volumes:
      - public-data:/usr/app/public
    depends_on:
      - db
    networks: 
      - public
      - private
    restart: on-failure

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: devdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks: 
      - private

volumes:
  postgres-data:
  public-data:
    driver: local
networks:
  public:
  private: